language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t risatoy17/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true risatoy17/docker-react npm run test -- --coverage
